-- XMonad configuration file by Aline Abler
import XMonad
import XMonad.Hooks.DynamicLog
import qualified XMonad.StackSet as W
import qualified Data.Map as M
import XMonad.Util.EZConfig ( additionalKeys, removeKeys )
import System.Exit
import XMonad.Hooks.EwmhDesktops
import XMonad.Hooks.ManageDocks
import XMonad.Layout.NoBorders
import XMonad.Layout.ToggleLayouts

myLayout = tiled ||| Mirror tiled ||| Full
  where
    -- default tiling algorithm partitions the screen into two panes
    tiled   = Tall nmaster delta ratio
    -- The default number of windows in the master pane
    nmaster = 1
    -- Default proportion of screen occupied by master pane
    ratio   = 1/2
    -- Percent of screen to increment by when resizing panes
    delta   = 3/100

main = xmonad =<< statusBar myBar myPP toggleGapsKey myConfig

-- main configuration for xmonad
myConfig = defaultConfig
    { terminal = "gnome-terminal"
    , modMask = mod4Mask -- use super key as modifier
    , borderWidth = 1
    , normalBorderColor = "#181715"
    , focusedBorderColor = "#58C5F1"
    , focusFollowsMouse = True
    -- , focusFollowsMouse = False
    , layoutHook = smartBorders $ layoutHook defaultConfig
    , handleEventHook = fullscreenEventHook
    } `additionalKeys` myKeys `removeKeys` [(mod4Mask, xK_q), (mod4Mask, xK_space)]

-- override some of the default keybindings and add my own
myKeys =
    [ ((mod4Mask,               xK_Return), spawn "gnome-terminal")
    , ((mod4Mask .|. shiftMask, xK_Return), windows W.swapMaster)
    , ((mod4Mask,               xK_slash ), sendMessage NextLayout)
    , ((mod4Mask .|. shiftMask, xK_slash ), sendMessage FirstLayout)
    , ((mod4Mask .|. shiftMask, xK_q), kill) -- close window with mod-shift-Q (default is mod-shift-C)
    , ((mod4Mask .|. shiftMask, xK_e), io (exitWith ExitSuccess)) -- close xmonad with mod-shift-E (default is mod-shift-Q)
    , ((mod4Mask .|. shiftMask, xK_r), spawn "if type xmonad; then xmonad --recompile && xmonad --restart; else xmessage xmonad not in \\$PATH: \"$PATH\"; fi") -- %! Recompile and restart xmonad
    , ((mod4Mask,               xK_x), spawn "scrot '%Y-%m-%d-%H%M%S.png' -b -u -e 'mv $f ~/Files/screenshots/'" ) -- take a screenshoft of the currently active window
    , ((mod4Mask .|. shiftMask, xK_x), spawn "scrot '%Y-%m-%d-%H%M%S-full.png' -b -e 'mv $f ~/Files/screenshots/'" ) -- take a screenshot (of everything)
    ]

-- use xmobar as status bar, overriding the default config file path
myBar = "xmobar /home/yan/.xmonad/xmobarrc"

-- configuration of the status bar output generated by xmonad
myPP = xmobarPP { ppCurrent = xmobarColor "#181715" "#58C5F1" . wrap "[" "]"
                , ppTitle = xmobarColor "#14FF08" "" . shorten 120
                , ppVisible = xmobarColor "#58C5F1" "#181715" . wrap "(" ")"
                , ppUrgent = xmobarColor "#181715" "#D81816"
                , ppHidden = xmobarColor "#58C5F1" "#181715"
                , ppSep = " * "
           }

-- keybinding for toggling the gap for the statusbar
toggleGapsKey XConfig {XMonad.modMask = mod4Mask} = (mod4Mask, xK_b)
